<?php
declare(strict_types=1);
require_once __DIR__ . '/lib.php';
require_admin();
$data = api_request('admin_status', [], true);
$webhooks = is_array($data['webhooks'] ?? null) ? $data['webhooks'] : [];
$templates = is_array($data['webhookTemplates'] ?? null) ? $data['webhookTemplates'] : [];
$issues = is_array($data['deliveryIssues'] ?? null) ? $data['deliveryIssues'] : [];
$csrf = csrf_token();
?>
<!doctype html><html lang="en"><head><meta charset="utf-8"><meta name="viewport" content="width=device-width, initial-scale=1"><?php render_head_meta('Webhooks — The Secretary Control Room','Configure Discord status notifications.','admin/webhooks',true); ?><link rel="stylesheet" href="/assets/style.css?v=3.0.0"></head>
<body class="admin-body"><?php render_admin_header('webhooks'); ?><main class="container wide admin-page">
<div class="admin-intro"><div><span class="eyebrow">Discord automation</span><h1>Webhooks.</h1><p>Create, alter, test, or remove notification destinations and message templates.</p></div></div><?php render_admin_nav('webhooks'); render_admin_flash(); ?>
<?php if ($issues): ?><section class="delivery-issues"><div><strong>Notification delivery needs attention</strong><p>These provider errors did not stop monitoring.</p></div><ul><?php foreach (array_slice($issues,0,8) as $issue): ?><li><span><?= h((string) ($issue['event'] ?? 'notification')) ?></span><strong><?= h((string) ($issue['title'] ?? 'Status event')) ?></strong><small><?= h((string) ($issue['error'] ?? 'Unknown delivery error')) ?> · <?= h(format_time($issue['attemptedAt'] ?? null)) ?></small></li><?php endforeach; ?></ul></section><?php endif; ?>
<section class="panel"><div class="panel-heading"><div><span class="eyebrow">Destinations and messages</span><h2>Webhook configuration</h2></div><span>Clear a URL to remove that webhook</span></div><form action="/action" method="post" class="stack-form"><input type="hidden" name="csrf" value="<?= h($csrf) ?>"><input type="hidden" name="return_to" value="/admin/webhooks"><input type="hidden" name="action" value="update_webhooks"><div class="webhook-grid"><label>HTTP downtime / recovery<input name="webhook_http" type="url" value="<?= h((string) ($webhooks['http'] ?? '')) ?>" placeholder="https://discord.com/api/webhooks/…"></label><label>Discord API status<input name="webhook_discord" type="url" value="<?= h((string) ($webhooks['discord'] ?? '')) ?>"></label><label>New posts<input name="webhook_post" type="url" value="<?= h((string) ($webhooks['post'] ?? '')) ?>"></label><label>Maintenance<input name="webhook_maintenance" type="url" value="<?= h((string) ($webhooks['maintenance'] ?? '')) ?>"></label></div><p class="field-label">Template placeholders: {timestamp}, {page_url}, {slug}, {title}</p><div class="webhook-grid"><?php foreach (['http_down'=>'HTTP downtime','http_up'=>'HTTP recovery','discord_limited'=>'Discord rate limited','discord_normal'=>'Discord normal','post'=>'New post','maintenance_start'=>'Maintenance started','maintenance_end'=>'Maintenance concluded'] as $key=>$label): ?><label class="template-field"><?= h($label) ?><textarea name="template_<?= h($key) ?>"><?= h((string) ($templates[$key] ?? '')) ?></textarea></label><?php endforeach; ?></div><div class="form-actions"><button class="button primary" type="submit">Save webhook automation</button></div></form><div class="webhook-tests"><span>Test saved destinations</span><?php foreach (['http'=>'HTTP','discord'=>'Discord API','post'=>'Posts','maintenance'=>'Maintenance'] as $kind=>$label): ?><form action="/action" method="post"><input type="hidden" name="csrf" value="<?= h($csrf) ?>"><input type="hidden" name="return_to" value="/admin/webhooks"><input type="hidden" name="action" value="test_webhook"><input type="hidden" name="kind" value="<?= h($kind) ?>"><button class="button small ghost" type="submit">Test <?= h($label) ?></button></form><?php endforeach; ?></div></section>
</main><script src="/assets/app.js?v=3.0.0" defer></script></body></html>
