<?php
declare(strict_types=1);
require_once __DIR__ . '/lib.php';
require_admin();
$data = api_request('admin_status', [], true);
$host = is_array($data['hostManagement'] ?? null) ? $data['hostManagement'] : [];
$servers = is_array($host['servers'] ?? null) ? $host['servers'] : [];
$switchState = is_array($host['switchState'] ?? null) ? $host['switchState'] : null;
$history = is_array($host['recentSwitches'] ?? null) ? $host['recentSwitches'] : [];
$csrf = csrf_token();
$manualLocked = !empty($host['manualRetryAt']) && strtotime((string) $host['manualRetryAt']) > time();
?>
<!doctype html><html lang="en"><head><meta charset="utf-8"><meta name="viewport" content="width=device-width, initial-scale=1"><?php render_head_meta('Servers — The Secretary Control Room','Private Render fleet and host-switch management.','admin/servers',true); ?><link rel="stylesheet" href="/assets/style.css?v=3.0.0"></head>
<body class="admin-body"><?php render_admin_header('servers'); ?><main class="container wide admin-page">
<div class="admin-intro"><div><span class="eyebrow">Infrastructure</span><h1>Server fleet.</h1><p>Bandwidth-aware automatic selection, manual switching, exclusions, and suspension state.</p></div><form action="/action" method="post"><input type="hidden" name="csrf" value="<?= h($csrf) ?>"><input type="hidden" name="return_to" value="/admin/servers"><input type="hidden" name="action" value="refresh_servers"><button class="button primary" type="submit">Refresh Render usage</button></form></div><?php render_admin_nav('servers'); render_admin_flash(); ?>
<?php if (!empty($host['emergency'])): ?><div class="host-emergency"><strong>Emergency stop is active</strong><p>Both automatic attempts failed. The controller will not start another automatic switch until service recovery or a manual switch.</p></div><?php endif; ?>
<?php if ($switchState): ?><section class="switch-progress"><div><span class="eyebrow">Switch in progress</span><h2><?= h(ucfirst((string) ($switchState['phase'] ?? 'working'))) ?></h2><p><?= h((string) ($switchState['reason'] ?? 'Host transition')) ?></p></div><div class="switch-progress-meta"><strong>Attempt <?= h((string) ($switchState['attempts'] ?? 1)) ?>/<?= h((string) ($switchState['maxAttempts'] ?? 2)) ?></strong><span><?= h((string) ($switchState['sourceKey'] ?? '—')) ?> → <?= h((string) ($switchState['targetKey'] ?? '—')) ?></span><?php if (!empty($switchState['validateAfter'])): ?><small>Validation <?= h(format_time((string) $switchState['validateAfter'])) ?></small><?php endif; ?></div></section><?php endif; ?>
<?php if ($manualLocked): ?><div class="fleet-note">Manual switching is rate-limited until <?= h(format_time((string) $host['manualRetryAt'])) ?>. Offline holds and inventory refresh remain available.</div><?php endif; ?>

<section class="server-grid"><?php if (!$servers): ?><div class="panel empty-card">No configured servers were returned. Add the Render Script Properties listed in the deployment guide.</div><?php else: foreach ($servers as $server):
  $active = !empty($server['active']); $offline = !empty($server['offlineUntil']); $errored = !empty($server['error']);
  $bandwidthPercent = isset($server['bandwidthRemainingPercent']) && is_numeric($server['bandwidthRemainingPercent']) ? max(0,min(100,(float)$server['bandwidthRemainingPercent'])) : null;
  $pipelineRemaining = $server['pipelineRemainingMinutesEstimate'] ?? null;
?><article class="server-card <?= $active ? 'is-active' : '' ?> <?= $offline ? 'is-offline' : '' ?>">
  <div class="server-card-head"><div><span class="server-region"><?= h((string) ($server['region'] ?? 'Render')) ?></span><h2><?= h((string) ($server['name'] ?? 'Server')) ?></h2></div><span class="status-pill <?= $active ? 'good' : ($offline || $errored ? 'bad' : 'unknown') ?>"><?= $active ? 'Active host' : ($offline ? 'Offline hold' : ($errored ? 'API error' : (!empty($server['suspended']) ? 'Suspended' : 'Standby'))) ?></span></div>
  <?php if ($errored): ?><div class="server-error"><?= h((string) $server['error']) ?></div><?php endif; ?>
  <?php if ($offline): ?><div class="offline-banner"><strong>Excluded until <?= h(format_time((string) $server['offlineUntil'])) ?></strong><span><?= h((string) ($server['offlineReason'] ?? 'No reason recorded')) ?></span></div><?php endif; ?>
  <div class="capacity-block"><div class="capacity-label"><span>Remaining bandwidth</span><strong><?= h(format_bytes_decimal($server['bandwidthRemainingBytes'] ?? null)) ?><?= $bandwidthPercent !== null ? ' · ' . h(number_format($bandwidthPercent,1)) . '%' : '' ?></strong></div><div class="capacity-track"><span style="width:<?= $bandwidthPercent !== null ? h(number_format($bandwidthPercent,2,'.','')) : '0' ?>%"></span></div></div>
  <div class="server-facts"><div><span>Pipeline remaining</span><strong><?= is_numeric($pipelineRemaining) ? h(number_format((float)$pipelineRemaining,0)) . ' min' : 'Unavailable' ?></strong><small>Estimated from this month’s deploy durations</small></div><div><span>Render state</span><strong><?= !empty($server['suspended']) ? 'Suspended' : 'Running' ?></strong><small><?= h((string) ($server['plan'] ?? 'Plan unavailable')) ?></small></div></div>
  <?php if (!$active && !$offline && !$errored): ?><form action="/action" method="post" class="server-switch-form" data-confirm="Begin a host switch to this server? The deployment and domain cutover will continue in the background."><input type="hidden" name="csrf" value="<?= h($csrf) ?>"><input type="hidden" name="return_to" value="/admin/servers"><input type="hidden" name="action" value="switch_server"><input type="hidden" name="server_key" value="<?= h((string) $server['key']) ?>"><label>Switch reason<input name="reason" required minlength="4" maxlength="500" placeholder="Testing, regional issue, manual recovery…"></label><button class="button primary full" type="submit" <?= ($manualLocked || $switchState) ? 'disabled' : '' ?>>Switch host to this server</button></form><?php endif; ?>
  <div class="server-hold-controls"><?php if ($offline): ?><form action="/action" method="post"><input type="hidden" name="csrf" value="<?= h($csrf) ?>"><input type="hidden" name="return_to" value="/admin/servers"><input type="hidden" name="action" value="clear_server_offline"><input type="hidden" name="server_key" value="<?= h((string) $server['key']) ?>"><button class="button small ghost" type="submit">Clear offline hold</button></form><?php else: ?><details><summary>Exclude from automatic selection</summary><form action="/action" method="post" class="stack-form compact"><input type="hidden" name="csrf" value="<?= h($csrf) ?>"><input type="hidden" name="return_to" value="/admin/servers"><input type="hidden" name="action" value="set_server_offline"><input type="hidden" name="server_key" value="<?= h((string) $server['key']) ?>"><label>Duration<select name="hours"><option value="24">24 hours</option><option value="48">48 hours</option></select></label><label>Reason<input name="reason" required minlength="4" maxlength="500"></label><button class="button small danger" type="submit">Apply offline hold</button></form></details><?php endif; ?></div>
</article><?php endforeach; endif; ?></section>

<section class="panel switch-history"><div class="panel-heading"><div><span class="eyebrow">Private audit</span><h2>Recent host switches</h2></div><span><?= count($history) ?> shown</span></div><div class="table-wrap"><table><thead><tr><th>Status</th><th>Mode</th><th>Route</th><th>Reason / result</th><th>Updated</th></tr></thead><tbody><?php if (!$history): ?><tr><td colspan="5" class="empty-cell">No host switches recorded.</td></tr><?php else: foreach ($history as $item): ?><tr><td><span class="mini-result <?= ($item['status'] ?? '') === 'completed' ? 'good' : (($item['status'] ?? '') === 'emergency' ? 'bad' : '') ?>"><?= h(strtoupper((string) ($item['status'] ?? 'working'))) ?></span></td><td><?= h(ucfirst((string) ($item['mode'] ?? 'automatic'))) ?></td><td><?= h((string) ($item['sourceKey'] ?? '—')) ?> → <?= h((string) ($item['targetKey'] ?? '—')) ?></td><td><?= h((string) ($item['message'] ?? $item['reason'] ?? '')) ?></td><td><?= h(format_time($item['updatedAt'] ?? null,'j M, g:i A')) ?></td></tr><?php endforeach; endif; ?></tbody></table></div></section>
<p class="fleet-disclaimer">Bandwidth comes from Render’s service metrics. Pipeline minutes are an estimate because Render does not expose the workspace’s exact remaining pipeline allowance through its public API.</p>
</main><script src="/assets/app.js?v=3.0.0" defer></script></body></html>
