<?php
declare(strict_types=1);
require_once __DIR__ . '/lib.php';
require_admin();
$data = api_request('admin_status', [], true);
$incidents = is_array($data['incidents'] ?? null) ? $data['incidents'] : [];
$csrf = csrf_token();
?>
<!doctype html><html lang="en"><head><meta charset="utf-8"><meta name="viewport" content="width=device-width, initial-scale=1"><?php render_head_meta('Incidents — The Secretary Control Room','Create and manage public incident pages.','admin/incidents',true); ?><link rel="stylesheet" href="/assets/style.css?v=3.0.0"></head>
<body class="admin-body"><?php render_admin_header('incidents'); ?><main class="container wide admin-page">
<div class="admin-intro"><div><span class="eyebrow">Publishing</span><h1>Incident desk.</h1><p>Create, update, resolve, and edit public incident reports.</p></div></div><?php render_admin_nav('incidents'); render_admin_flash(); ?>
<div class="admin-grid">
  <section class="panel span-5"><div class="panel-heading"><div><span class="eyebrow">New incident</span><h2>Publish a report</h2></div></div><form action="/action" method="post" class="stack-form" data-editor-form><input type="hidden" name="csrf" value="<?= h($csrf) ?>"><input type="hidden" name="return_to" value="/admin/incidents"><input type="hidden" name="action" value="create_incident"><label>Title<input name="title" data-slug-title maxlength="120" required></label><div class="split-fields"><label>Slug<input name="slug" data-slug-input pattern="[a-z0-9][a-z0-9-]{0,119}"></label><label>Impact<select name="impact"><option value="minor">Minor</option><option value="major">Major</option><option value="critical">Critical</option></select></label></div><label>First update<textarea name="message" rows="4" maxlength="3000" required></textarea></label><label>Public summary<input name="excerpt" maxlength="300"></label><label>Full incident page</label><?php render_rich_editor('content_html'); ?><div class="form-actions"><button class="button primary" type="submit">Publish incident</button></div></form></section>
  <section class="panel span-7"><div class="panel-heading"><div><span class="eyebrow">History</span><h2>Incident pages</h2></div><span><?= count($incidents) ?> total</span></div><div class="manage-list"><?php if (!$incidents): ?><div class="empty-card">No incidents yet.</div><?php else: foreach ($incidents as $incident): ?><article class="manage-item"><div class="manage-summary"><div><span class="status-pill <?= h(($incident['status'] ?? '') === 'resolved' ? 'good' : (($incident['impact'] ?? '') === 'critical' ? 'bad' : 'warn')) ?>"><?= h(ucfirst((string) ($incident['status'] ?? 'open'))) ?></span><h3><?= h((string) ($incident['title'] ?? 'Incident')) ?></h3><p><?= h(format_time($incident['startedAt'] ?? null)) ?> · /incidents/<?= h((string) ($incident['slug'] ?? '')) ?></p></div><a class="button small ghost" href="/incidents/<?= h((string) ($incident['slug'] ?? '')) ?>" target="_blank" rel="noopener">Open ↗</a></div><?php if (($incident['status'] ?? '') !== 'resolved'): ?><form action="/action" method="post" class="inline-update"><input type="hidden" name="csrf" value="<?= h($csrf) ?>"><input type="hidden" name="return_to" value="/admin/incidents"><input type="hidden" name="action" value="add_incident_update"><input type="hidden" name="id" value="<?= h((string) ($incident['id'] ?? '')) ?>"><select name="status"><option value="investigating">Investigating</option><option value="identified">Identified</option><option value="monitoring">Monitoring</option><option value="resolved">Resolved</option></select><textarea name="message" rows="2" maxlength="3000" required placeholder="Write a public update…"></textarea><button class="button small primary" type="submit">Publish</button></form><?php endif; ?><details><summary>Edit page</summary><form action="/action" method="post" class="stack-form" data-editor-form><input type="hidden" name="csrf" value="<?= h($csrf) ?>"><input type="hidden" name="return_to" value="/admin/incidents"><input type="hidden" name="action" value="edit_content"><input type="hidden" name="type" value="incident"><input type="hidden" name="id" value="<?= h((string) ($incident['id'] ?? '')) ?>"><div class="split-fields"><label>Title<input name="title" value="<?= h((string) ($incident['title'] ?? '')) ?>" required></label><label>Slug<input name="slug" value="<?= h((string) ($incident['slug'] ?? '')) ?>" required></label></div><label>Summary<input name="excerpt" value="<?= h((string) ($incident['excerpt'] ?? '')) ?>"></label><?php render_rich_editor('content_html',(string)($incident['contentHtml'] ?? '')); ?><button class="button primary" type="submit">Save page</button></form></details></article><?php endforeach; endif; ?></div></section>
</div></main><script src="/assets/app.js?v=3.0.0" defer></script></body></html>
