<?php
declare(strict_types=1);
require_once __DIR__ . '/lib.php';
require_admin();
$data = api_request('admin_status', [], true);
$posts = is_array($data['posts'] ?? null) ? $data['posts'] : [];
$csrf = csrf_token();
?>
<!doctype html><html lang="en"><head><meta charset="utf-8"><meta name="viewport" content="width=device-width, initial-scale=1"><?php render_head_meta('Posts — The Secretary Control Room','Create and manage status posts.','admin/posts',true); ?><link rel="stylesheet" href="/assets/style.css?v=3.0.0"></head>
<body class="admin-body"><?php render_admin_header('posts'); ?><main class="container wide admin-page">
<div class="admin-intro"><div><span class="eyebrow">Editorial</span><h1>System posts.</h1><p>Publish, alter, redeliver, or remove public updates.</p></div></div><?php render_admin_nav('posts'); render_admin_flash(); ?>
<div class="admin-grid">
  <section class="panel span-5"><div class="panel-heading"><div><span class="eyebrow">New post</span><h2>Publish an update</h2></div></div><form action="/action" method="post" class="stack-form" data-editor-form><input type="hidden" name="csrf" value="<?= h($csrf) ?>"><input type="hidden" name="return_to" value="/admin/posts"><input type="hidden" name="action" value="create_post"><label>Title<input name="title" data-slug-title maxlength="120" required></label><label>Slug<input name="slug" data-slug-input pattern="[a-z0-9][a-z0-9-]{0,119}"></label><label>Card excerpt<input name="excerpt" maxlength="300" required></label><label>Post body</label><?php render_rich_editor('content_html'); ?><div class="form-actions"><button class="button primary" type="submit">Publish post</button></div></form></section>
  <section class="panel span-7"><div class="panel-heading"><div><span class="eyebrow">Library</span><h2>Published posts</h2></div><span><?= count($posts) ?> total</span></div><div class="manage-list"><?php if (!$posts): ?><div class="empty-card">No posts yet.</div><?php else: foreach ($posts as $post): ?><article class="manage-item"><div class="manage-summary"><div><span class="status-pill good">Published</span><h3><?= h((string) ($post['title'] ?? 'Post')) ?></h3><p><?= h(format_time($post['publishedAt'] ?? null)) ?> · /posts/<?= h((string) ($post['slug'] ?? '')) ?></p></div><a class="button small ghost" href="/posts/<?= h((string) ($post['slug'] ?? '')) ?>" target="_blank" rel="noopener">Open ↗</a></div><div class="manage-actions"><form action="/action" method="post" data-confirm="Resend this post to Discord?"><input type="hidden" name="csrf" value="<?= h($csrf) ?>"><input type="hidden" name="return_to" value="/admin/posts"><input type="hidden" name="action" value="resend_post_discord"><input type="hidden" name="id" value="<?= h((string) ($post['id'] ?? '')) ?>"><button class="button small ghost" type="submit">Resend Discord</button></form><form action="/action" method="post" data-confirm="Resend this post by email?"><input type="hidden" name="csrf" value="<?= h($csrf) ?>"><input type="hidden" name="return_to" value="/admin/posts"><input type="hidden" name="action" value="resend_post_email"><input type="hidden" name="id" value="<?= h((string) ($post['id'] ?? '')) ?>"><button class="button small ghost" type="submit">Resend email</button></form><form action="/action" method="post" data-confirm="Permanently delete this post?"><input type="hidden" name="csrf" value="<?= h($csrf) ?>"><input type="hidden" name="return_to" value="/admin/posts"><input type="hidden" name="action" value="delete_post"><input type="hidden" name="id" value="<?= h((string) ($post['id'] ?? '')) ?>"><button class="button small danger" type="submit">Delete</button></form></div><details><summary>Edit post</summary><form action="/action" method="post" class="stack-form" data-editor-form><input type="hidden" name="csrf" value="<?= h($csrf) ?>"><input type="hidden" name="return_to" value="/admin/posts"><input type="hidden" name="action" value="edit_content"><input type="hidden" name="type" value="post"><input type="hidden" name="id" value="<?= h((string) ($post['id'] ?? '')) ?>"><div class="split-fields"><label>Title<input name="title" value="<?= h((string) ($post['title'] ?? '')) ?>" required></label><label>Slug<input name="slug" value="<?= h((string) ($post['slug'] ?? '')) ?>" required></label></div><label>Excerpt<input name="excerpt" value="<?= h((string) ($post['excerpt'] ?? '')) ?>" required></label><?php render_rich_editor('content_html',(string)($post['contentHtml'] ?? '')); ?><button class="button primary" type="submit">Save post</button></form></details></article><?php endforeach; endif; ?></div></section>
</div></main><script src="/assets/app.js?v=3.0.0" defer></script></body></html>
