<?php
declare(strict_types=1);
require_once __DIR__ . '/lib.php';
$category = (string) ($_GET['category'] ?? '');
if ($category !== '' && !isset(COMMUNITY_CATEGORIES[$category])) $category = '';
$sort = in_array((string) ($_GET['sort'] ?? ''), ['newest', 'votes'], true) ? (string) $_GET['sort'] : 'activity';
$topics = community_forum_topics($category, $sort);
$viewer = current_user();
$flash = community_take_flash();
?>
<!doctype html><html lang="en"><head><meta charset="utf-8"><meta name="viewport" content="width=device-width, initial-scale=1"><meta name="theme-color" content="#050506"><?php render_head_meta('Forums — The Secretary Community', 'Discuss suggestions, bugs, website errors, fatal errors, and downtime.', 'forums'); ?><link rel="stylesheet" href="/assets/style.css?v=3.1.0"></head><body><?php render_site_header('forums'); ?>
<main class="container page forum-page">
  <section class="forum-hero"><div><span class="eyebrow">The Secretary community</span><h1>Forums</h1><p>Report what broke, suggest what comes next, and help each other understand what is happening.</p></div><?php if ($viewer): ?><button class="button primary" type="button" data-open-topic>Start a discussion</button><?php else: ?><a class="button primary" href="/login?return=%2Fforums">Log in to post</a><?php endif; ?></section>
  <?php if ($flash): ?><div class="flash <?= h((string) $flash['type']) ?>"><?= h((string) $flash['message']) ?></div><?php endif; ?>
  <?php if (!community_db_configured()): ?><div class="community-unavailable large"><strong>Community database not connected</strong><p>Import <code>database.sql</code> and enter the InfinityFree database values in <code>config.php</code>. The public status system remains available independently.</p></div><?php else: ?>
  <div class="forum-layout"><aside class="forum-sidebar"><a class="forum-side-main<?= $category === '' ? ' active' : '' ?>" href="/forums"><span>◈</span><strong>All discussions</strong><small><?= count($topics) ?> shown</small></a><div class="forum-side-title">Categories</div><?php foreach (COMMUNITY_CATEGORIES as $key => [$label, $description, $color]): ?><a class="forum-category-link<?= $category === $key ? ' active' : '' ?>" href="/forums?category=<?= h($key) ?>"><span style="--category-color:<?= h($color) ?>"></span><div><strong><?= h($label) ?></strong><small><?= h($description) ?></small></div></a><?php endforeach; ?><div class="forum-guidance"><strong>Before posting</strong><p>Include what happened, what you expected, and any steps that reproduce it. Never post passwords or API keys.</p></div></aside>
    <section class="forum-feed"><header class="forum-feed-head"><div><strong><?= $category ? h(community_category($category)[0]) : 'Latest discussions' ?></strong><span><?= count($topics) ?> topic<?= count($topics) === 1 ? '' : 's' ?></span></div><nav aria-label="Sort topics"><a class="<?= $sort === 'activity' ? 'active' : '' ?>" href="?<?= $category ? 'category=' . rawurlencode($category) . '&amp;' : '' ?>sort=activity">Activity</a><a class="<?= $sort === 'newest' ? 'active' : '' ?>" href="?<?= $category ? 'category=' . rawurlencode($category) . '&amp;' : '' ?>sort=newest">Newest</a><a class="<?= $sort === 'votes' ? 'active' : '' ?>" href="?<?= $category ? 'category=' . rawurlencode($category) . '&amp;' : '' ?>sort=votes">Top</a></nav></header><div class="forum-topic-columns" aria-hidden="true"><span>Topic</span><span>Votes</span><span>Replies</span><span>Activity</span></div><div class="forum-topic-list">
      <?php if (!$topics): ?><div class="community-empty"><span>◇</span><p>No discussions in this category yet.</p></div><?php endif; ?>
      <?php foreach ($topics as $topic): [$catLabel, , $catColor] = community_category((string) $topic['category']); ?><article class="forum-topic-row"><div class="forum-topic-primary"><?= community_render_avatar($topic, 'medium') ?><div><div class="forum-topic-title-line"><?php if ($topic['status'] === 'solved'): ?><span class="topic-state solved">✓ Solved</span><?php elseif ($topic['status'] === 'closed'): ?><span class="topic-state closed">Closed</span><?php endif; ?><a href="/forums/<?= h((string) $topic['slug']) ?>"><?= h((string) $topic['title']) ?></a></div><p><?= h(community_substr((string) $topic['body'], 0, 180)) ?><?= community_strlen((string) $topic['body']) > 180 ? '…' : '' ?></p><span class="forum-topic-category" style="--category-color:<?= h($catColor) ?>"><?= h($catLabel) ?> · by @<?= h((string) $topic['username']) ?></span></div></div><strong class="forum-stat"><?= (int) $topic['vote_score'] ?></strong><strong class="forum-stat"><?= (int) $topic['reply_count'] ?></strong><time datetime="<?= h((string) $topic['updated_at']) ?>"><?= h(community_relative_time((string) $topic['updated_at'])) ?></time></article><?php endforeach; ?>
    </div></section></div><?php endif; ?>
</main>
<?php if ($viewer): ?><dialog class="topic-dialog" data-topic-dialog><form method="post" action="/community-action" class="topic-form"><input type="hidden" name="csrf" value="<?= h(csrf_token()) ?>"><input type="hidden" name="action" value="create_topic"><input type="hidden" name="return_to" value="/forums"><header><div><span class="eyebrow">New discussion</span><h2>Start with the useful details.</h2></div><button class="dialog-close" type="button" data-close-topic>×</button></header><label>Category<select name="category" required><?php foreach (COMMUNITY_CATEGORIES as $key => [$label]): ?><option value="<?= h($key) ?>"<?= $category === $key ? ' selected' : '' ?>><?= h($label) ?></option><?php endforeach; ?></select></label><label>Title<input name="title" required minlength="6" maxlength="160" placeholder="Summarize the issue or idea"></label><label>Details<textarea name="body" required minlength="10" maxlength="20000" rows="10" placeholder="What happened? What did you expect? Add steps or context that will help others respond."></textarea></label><div class="topic-form-note">Public discussion · do not include credentials or private data.</div><div class="form-actions"><button class="button ghost" type="button" data-close-topic>Cancel</button><button class="button primary" type="submit">Publish discussion</button></div></form></dialog><?php endif; ?>
<?php render_site_footer(); ?><script src="/assets/app.js?v=3.1.0" defer></script></body></html>
