<?php
declare(strict_types=1);
require_once __DIR__ . '/lib.php';
$slug = strtolower(trim((string) ($_GET['slug'] ?? '')));
$topic = preg_match('/^[a-z0-9][a-z0-9-]{0,189}$/', $slug) ? community_topic_by_slug($slug, true) : null;
if (!$topic) http_response_code(404);
$replies = $topic ? community_topic_replies((int) $topic['id']) : [];
$viewer = current_user();
$isOp = $viewer && $topic && (int) $viewer['id'] === (int) $topic['user_id'];
$flash = community_take_flash();
[$categoryLabel, $categoryDescription, $categoryColor] = community_category((string) ($topic['category'] ?? ''));
$replyById = []; foreach ($replies as $entry) $replyById[(int) $entry['id']] = $entry;
?>
<!doctype html><html lang="en"><head><meta charset="utf-8"><meta name="viewport" content="width=device-width, initial-scale=1"><meta name="theme-color" content="#050506"><?php render_head_meta(($topic ? (string) $topic['title'] : 'Discussion unavailable') . ' — Forums', $topic ? community_substr((string) $topic['body'], 0, 160) : 'This forum discussion is unavailable.', $topic ? 'forums/' . $slug : 'forums', !$topic); ?><link rel="stylesheet" href="/assets/style.css?v=3.1.0"></head><body><?php render_site_header('forums'); ?>
<main class="container page topic-page"><?php if (!$topic): ?><section class="not-found-panel"><span class="eyebrow">404</span><h1>Discussion unavailable</h1><p>It may have been removed or the community database may not be connected.</p><a class="button primary" href="/forums">Return to forums</a></section><?php else: ?>
  <nav class="topic-breadcrumb"><a href="/forums">Forums</a><span>›</span><a href="/forums?category=<?= h((string) $topic['category']) ?>"><?= h($categoryLabel) ?></a></nav>
  <?php if ($flash): ?><div class="flash <?= h((string) $flash['type']) ?>"><?= h((string) $flash['message']) ?></div><?php endif; ?>
  <header class="topic-title-block"><div><span class="forum-topic-category" style="--category-color:<?= h($categoryColor) ?>"><?= h($categoryLabel) ?></span><h1><?= h((string) $topic['title']) ?></h1><p>Started by <button type="button" data-profile-user="<?= h((string) $topic['username']) ?>">@<?= h((string) $topic['username']) ?></button> · <?= h(community_relative_time((string) $topic['created_at'])) ?></p></div><div class="topic-head-meta"><strong><?= (int) $topic['reply_count'] ?></strong><span>replies</span><strong><?= (int) $topic['views'] ?></strong><span>views</span></div></header>
  <div class="topic-discussion"><article class="forum-message op-message" id="original-post"><aside><?= community_render_avatar($topic, 'large') ?><strong><?= h((string) $topic['display_name']) ?></strong><span>@<?= h((string) $topic['username']) ?></span><small>Original poster</small></aside><div class="forum-message-content"><header><span>Original post</span><time datetime="<?= h((string) $topic['created_at']) ?>"><?= h(community_format_date((string) $topic['created_at'])) ?></time></header><div class="forum-copy"><?= nl2br(h((string) $topic['body'])) ?></div><footer><form method="post" action="/community-action" class="vote-control"><input type="hidden" name="csrf" value="<?= h(csrf_token()) ?>"><input type="hidden" name="action" value="vote_topic"><input type="hidden" name="topic_id" value="<?= (int) $topic['id'] ?>"><input type="hidden" name="return_to" value="/forums/<?= h($slug) ?>#original-post"><button name="vote" value="1" type="submit"<?= !$viewer ? ' disabled title="Log in to vote"' : '' ?>>▲</button><strong><?= (int) $topic['vote_score'] ?></strong><button name="vote" value="-1" type="submit"<?= !$viewer ? ' disabled title="Log in to vote"' : '' ?>>▼</button></form><?php if ($viewer && $topic['status'] !== 'closed'): ?><button class="message-reply-button" type="button" data-reply-to="0" data-reply-name="<?= h((string) $topic['display_name']) ?>">Reply</button><?php endif; ?><?php if ($isOp): ?><form method="post" action="/community-action" class="topic-owner-control"><input type="hidden" name="csrf" value="<?= h(csrf_token()) ?>"><input type="hidden" name="action" value="toggle_topic"><input type="hidden" name="topic_id" value="<?= (int) $topic['id'] ?>"><input type="hidden" name="return_to" value="/forums/<?= h($slug) ?>"><button class="button small ghost" type="submit"><?= $topic['status'] === 'closed' ? 'Reopen discussion' : 'Close discussion' ?></button></form><?php endif; ?></footer></div></article>
  <?php foreach ($replies as $reply): $isSolution = (int) ($topic['solution_reply_id'] ?? 0) === (int) $reply['id']; $parent = $reply['parent_id'] ? ($replyById[(int) $reply['parent_id']] ?? null) : null; ?><article class="forum-message<?= $parent ? ' nested-reply' : '' ?><?= $isSolution ? ' solution-reply' : '' ?>" id="reply-<?= (int) $reply['id'] ?>"><aside><?= community_render_avatar($reply, 'large') ?><strong><?= h((string) $reply['display_name']) ?></strong><span>@<?= h((string) $reply['username']) ?></span><?php if ((int) $reply['user_id'] === (int) $topic['user_id']): ?><small>Original poster</small><?php endif; ?></aside><div class="forum-message-content"><header><?php if ($isSolution): ?><span class="solution-label">✓ Accepted solution</span><?php elseif ($parent): ?><a href="#reply-<?= (int) $parent['id'] ?>">Replying to @<?= h((string) $parent['username']) ?></a><?php else: ?><span>Reply</span><?php endif; ?><time datetime="<?= h((string) $reply['created_at']) ?>"><?= h(community_format_date((string) $reply['created_at'])) ?></time></header><div class="forum-copy"><?= !empty($reply['is_deleted']) ? '<em>This reply was deleted.</em>' : nl2br(h((string) $reply['body'])) ?></div><?php if (empty($reply['is_deleted'])): ?><footer><form method="post" action="/community-action" class="vote-control"><input type="hidden" name="csrf" value="<?= h(csrf_token()) ?>"><input type="hidden" name="action" value="vote_reply"><input type="hidden" name="reply_id" value="<?= (int) $reply['id'] ?>"><input type="hidden" name="return_to" value="/forums/<?= h($slug) ?>#reply-<?= (int) $reply['id'] ?>"><button name="vote" value="1" type="submit"<?= !$viewer ? ' disabled' : '' ?>>▲</button><strong><?= (int) $reply['vote_score'] ?></strong><button name="vote" value="-1" type="submit"<?= !$viewer ? ' disabled' : '' ?>>▼</button></form><?php if ($viewer && $topic['status'] !== 'closed'): ?><button class="message-reply-button" type="button" data-reply-to="<?= (int) $reply['id'] ?>" data-reply-name="<?= h((string) $reply['display_name']) ?>">Reply</button><?php endif; ?><?php if ($isOp && !$isSolution): ?><form method="post" action="/community-action"><input type="hidden" name="csrf" value="<?= h(csrf_token()) ?>"><input type="hidden" name="action" value="mark_solution"><input type="hidden" name="topic_id" value="<?= (int) $topic['id'] ?>"><input type="hidden" name="reply_id" value="<?= (int) $reply['id'] ?>"><input type="hidden" name="return_to" value="/forums/<?= h($slug) ?>#reply-<?= (int) $reply['id'] ?>"><button class="solution-button" type="submit">Mark as solution</button></form><?php endif; ?></footer><?php endif; ?></div></article><?php endforeach; ?></div>
  <?php if ($viewer && $topic['status'] !== 'closed'): ?><section class="reply-composer" id="reply"><div class="replying-to" data-replying-to hidden>Replying to <strong></strong><button type="button" data-clear-reply>×</button></div><form method="post" action="/community-action"><input type="hidden" name="csrf" value="<?= h(csrf_token()) ?>"><input type="hidden" name="action" value="reply"><input type="hidden" name="topic_id" value="<?= (int) $topic['id'] ?>"><input type="hidden" name="parent_id" value="0" data-parent-reply><input type="hidden" name="return_to" value="/forums/<?= h($slug) ?>#reply"><div><?= community_render_avatar($viewer, 'medium', false) ?><strong>Join the discussion</strong></div><textarea name="body" maxlength="10000" rows="6" required placeholder="Write a thoughtful reply…" data-reply-body></textarea><footer><small>Replies are public. Never include credentials.</small><button class="button primary" type="submit">Post reply</button></footer></form></section><?php elseif (!$viewer): ?><div class="comment-login-callout"><div><strong>Want to reply or vote?</strong><p>Log in to join this discussion.</p></div><a class="button primary" href="/login?return=<?= rawurlencode('/forums/' . $slug) ?>">Log in</a></div><?php else: ?><div class="topic-closed-note">This discussion is closed. The original poster can reopen it.</div><?php endif; ?>
<?php endif; ?></main><?php render_site_footer(); ?><script src="/assets/app.js?v=3.1.0" defer></script></body></html>
