<?php
$responseSeries = is_array($response['series'] ?? null) ? $response['series'] : [];
$responseSeriesJson = json_encode($responseSeries, JSON_UNESCAPED_SLASHES | JSON_UNESCAPED_UNICODE);
$responseHours = is_numeric($response['periodHours'] ?? null) ? (int) $response['periodHours'] : 48;
$checkIntervalMinutes = max(1, (int) ($monitor['checkIntervalMinutes'] ?? 5));
$maintenanceOnly = $currentStatus === 'maintenance';
$heroStatus = $maintenanceOnly ? 'operational' : $currentStatus;
$heroClass = status_class($heroStatus);
$heroHeadline = $maintenanceOnly ? 'Core systems are online' : $headline;
$heroText = $maintenanceOnly ? 'A planned maintenance window is active.' : $summaryText;
$discordRateLimited = !empty($discordApi['rateLimited']) || !empty($discordApi['rate_limited']);
$discordState = $discordRateLimited ? 'rate_limited' : (string) ($discordApi['state'] ?? 'unknown');
$discordCheckedAt = $discordApi['checkedAt'] ?? $discordApi['checked_at'] ?? null;
$latestResolved = array_slice($resolved, 0, 5);
$latestMaintenance = array_slice($maintenance, 0, 5);
$latestPosts = array_slice($posts, 0, 6);
?>
<main class="container page" id="status" data-status-content data-feed-state="<?= !empty($state['usingCached']) ? 'cached' : (!empty($state['available']) ? 'live' : 'unavailable') ?>" data-backend-error="<?= h((string) ($state['backendError'] ?? '')) ?>" data-diagnostic="<?= h((string) json_encode($state['diagnostic'] ?? [], JSON_UNESCAPED_SLASHES | JSON_UNESCAPED_UNICODE)) ?>" data-generated-at="<?= h((string) ($data['generatedAt'] ?? '')) ?>" data-last-check-at="<?= h((string) ($monitor['lastCheckAt'] ?? '')) ?>" data-check-interval-minutes="<?= h((string) $checkIntervalMinutes) ?>">
  <section class="status-intro">
    <div class="page-kicker"><span class="eyebrow">Live systems</span><span class="live-indicator"><span class="status-dot"></span>Continuously monitored</span></div>
    <div class="status-title-row"><div><h1>System status.</h1><p>Live availability, Discord API health, incident reports, and engineering updates for The Secretary.</p></div><button class="button primary subscribe-trigger" type="button" data-open-subscribe>Subscribe to updates</button></div>
  </section>

  <section class="status-hero <?= h($heroClass) ?>">
    <div class="hero-copy"><span class="status-pill <?= h($heroClass) ?>"><span class="status-dot"></span><?= h(status_label($heroStatus)) ?></span><h2><?= h($heroHeadline) ?></h2><p><?= h($heroText) ?></p><div class="last-checked">Last checked <time data-live-last-updated datetime="<?= h((string) ($monitor['lastCheckAt'] ?? '')) ?>"><?= h(format_time($monitor['lastCheckAt'] ?? null)) ?></time></div></div>
    <div class="hero-signal" aria-hidden="true"><span></span><span></span><span></span><span></span><span></span><span></span></div>
  </section>

  <?php if (!empty($state['usingCached'])): ?><aside class="feed-warning"><span>!</span><div><strong>Live feed temporarily delayed</strong><p>Showing the last successful monitor snapshot from <?= h(format_time(is_string($state['cachedAt'] ?? null) ? $state['cachedAt'] : null)) ?>. Automated checks continue independently.</p></div></aside><?php endif; ?>

  <?php if ($activeMaintenance): ?><aside class="maintenance-notice"><span class="notice-icon">⚙</span><div><strong>Maintenance in progress</strong><p>Some systems may not work to their fullest while planned work is completed.</p></div><a href="/maintenance">View maintenance →</a></aside><?php endif; ?>

  <section class="trust-strip" aria-label="Monitoring facts"><div><span class="fact-icon">↻</span><p><strong>Checked every <?= h((string) $checkIntervalMinutes) ?> minutes</strong><small>Automatically checked without relying on page visits.</small></p></div><div><span class="fact-icon">◎</span><p><strong><?= h(percent_or_dash($uptime['30'] ?? null)) ?> uptime</strong><small>Measured over the last 30 days.</small></p></div><div><span class="fact-icon">⌁</span><p><strong><?= h(format_duration_ms($monitor['responseMs'] ?? null)) ?> response</strong><small>Latest completed HTTP request.</small></p></div></section>

  <section class="section-block" aria-labelledby="services-title"><div class="section-heading"><div><span class="eyebrow">Live health</span><h2 id="services-title">Systems</h2></div><span class="section-count">2 signals</span></div><div class="system-list"><article class="system-row"><div class="system-ident"><span class="system-icon">S</span><div><h3>The Secretary service</h3><p>Commands, dashboard, web forms, and bot infrastructure.</p></div></div><div class="system-meta"><small><?= h(format_duration_ms($monitor['responseMs'] ?? null)) ?></small><span class="status-pill <?= h($heroClass) ?>"><span class="status-dot"></span><?= h(status_label($heroStatus)) ?></span></div></article><article class="system-row"><div class="system-ident"><span class="system-icon discord">D</span><div><h3>Discord API</h3><p>Low-frequency bot-authenticated rate-limit probe.</p></div></div><div class="system-meta"><small><?= h(format_time(is_string($discordCheckedAt) ? $discordCheckedAt : null, 'j M, g:i A')) ?></small><span class="status-pill <?= $discordRateLimited ? 'bad' : ($discordState === 'operational' ? 'good' : 'unknown') ?>"><span class="status-dot"></span><?= $discordRateLimited ? 'Rate limited' : ($discordState === 'operational' ? 'Operational' : 'Awaiting signal') ?></span></div></article></div></section>

  <section class="section-block analytics-section" aria-labelledby="uptime-title"><div class="section-heading"><div><span class="eyebrow">Measured availability</span><h2 id="uptime-title">Uptime and response</h2></div><span class="section-count">Completed checks only</span></div><div class="analytics-grid"><div class="uptime-panel"><div class="overall-uptime-grid"><article><strong><?= h(percent_or_dash($uptime['24h'] ?? null)) ?></strong><span>24 hours</span></article><article><strong><?= h(percent_or_dash($uptime['7'] ?? null)) ?></strong><span>7 days</span></article><article><strong><?= h(percent_or_dash($uptime['30'] ?? null)) ?></strong><span>30 days</span></article><article><strong><?= h(percent_or_dash($uptime['90'] ?? null)) ?></strong><span>90 days</span></article></div><div class="history-head"><small>Last 120 days</small><strong><?= h(percent_or_dash($uptime['120'] ?? null)) ?> <span>uptime</span></strong></div><div class="history-bars" aria-label="120-day uptime history"><?php foreach ($history as $day): $dayUptime = $day['uptime'] ?? null; $dayClass = !is_numeric($dayUptime) ? 'no-data' : ((float) $dayUptime >= 99.999 ? 'up' : ((float) $dayUptime >= 98 ? 'partial' : 'down')); $tip = format_time((string) ($day['date'] ?? ''), 'j M Y') . ' · ' . (is_numeric($dayUptime) ? number_format((float) $dayUptime, 3) . '% uptime' : 'No monitoring data'); ?><span class="history-day <?= h($dayClass) ?>" data-tooltip="<?= h($tip) ?>" aria-label="<?= h($tip) ?>"></span><?php endforeach; ?></div><div class="history-axis"><span>120 days ago</span><span>Today</span></div></div><article class="response-chart-card" data-response-chart data-series="<?= h((string) $responseSeriesJson) ?>"><div class="chart-card-head"><div><strong>Response time</strong><span>Last <?= h((string) $responseHours) ?> hours</span></div><small><?= h((string) ($response['samples'] ?? 0)) ?> samples</small></div><div class="chart-stage"><canvas data-response-canvas role="img" aria-label="Response-time history"></canvas><span class="response-hover-dot" data-response-hover-dot aria-hidden="true"></span><div class="chart-empty<?= $responseSeries ? ' is-hidden' : '' ?>">Response history appears after completed checks.</div></div><div class="response-stats"><div><strong><?= h(format_duration_ms($response['averageMs'] ?? null)) ?></strong><span>Average</span></div><div><strong><?= h(format_duration_ms($response['maximumMs'] ?? null)) ?></strong><span>Maximum</span></div><div><strong><?= h(format_duration_ms($response['minimumMs'] ?? null)) ?></strong><span>Minimum</span></div></div></article></div></section>

  <section class="section-block infrastructure-section"><div class="section-heading"><div><span class="eyebrow">Regional footprint</span><h2>Global infrastructure</h2></div><span class="section-count">8 active nodes</span></div><p class="section-copy">The Secretary operates across three regions for responsive, resilient service.</p><article class="infrastructure-card"><div class="infrastructure-map" role="img" aria-label="Five nodes in India, two in Singapore, and one in Virginia, United States"><img src="/assets/images/world-map.svg" alt="" aria-hidden="true"><span class="map-point virginia">1<small>Virginia</small></span><span class="map-point india">5<small>India</small></span><span class="map-point singapore">2<small>Singapore</small></span></div><div class="region-grid"><div><span></span><strong>India</strong><small>5 nodes</small></div><div><span></span><strong>Singapore</strong><small>2 nodes</small></div><div><span></span><strong>Virginia, US</strong><small>1 node</small></div></div></article></section>

  <?php if ($unresolved): ?><section class="section-block critical-section"><div class="section-heading"><div><span class="eyebrow">Requires attention</span><h2>Active incidents</h2></div><span class="section-count"><?= count($unresolved) ?> open</span></div><div class="timeline-list"><?php foreach (array_slice($unresolved, 0, 5) as $incident): $slug = (string) ($incident['slug'] ?? ''); ?><a class="timeline-card incident <?= h((string) ($incident['impact'] ?? 'minor')) ?>" <?= $slug ? 'href="/incidents/' . h($slug) . '"' : '' ?>><div class="timeline-title"><div><span class="status-pill <?= h(($incident['impact'] ?? '') === 'critical' ? 'bad' : 'warn') ?>"><?= h(ucfirst((string) ($incident['status'] ?? 'investigating'))) ?></span><h3><?= h((string) ($incident['title'] ?? 'Service incident')) ?></h3></div><time><?= h(format_time($incident['startedAt'] ?? null)) ?></time></div><p><?= h((string) (($incident['updates'][0]['message'] ?? '') ?: 'Investigation is in progress.')) ?></p><span class="card-link">Open incident →</span></a><?php endforeach; ?></div></section><?php endif; ?>

  <section class="section-block"><div class="section-heading"><div><span class="eyebrow">What happened</span><h2>Latest incidents</h2></div><a class="section-link" href="/incidents">View all incidents →</a></div><div class="entry-list"><?php if (!$latestResolved): ?><div class="empty-card">No resolved incidents have been recorded.</div><?php else: foreach ($latestResolved as $incident): $slug = (string) ($incident['slug'] ?? ''); ?><a class="entry-row" <?= $slug ? 'href="/incidents/' . h($slug) . '"' : '' ?>><span class="entry-date"><?= h(format_time($incident['resolvedAt'] ?? $incident['startedAt'] ?? null, 'j M Y')) ?></span><div><h3><?= h((string) ($incident['title'] ?? 'Incident')) ?></h3><p><?= h(ucfirst((string) ($incident['impact'] ?? 'minor'))) ?> impact · <?= h(ucfirst((string) ($incident['status'] ?? 'resolved'))) ?></p></div><span class="entry-arrow">↗</span></a><?php endforeach; endif; ?></div></section>

  <section class="section-block"><div class="section-heading"><div><span class="eyebrow">Planned work</span><h2>Maintenance</h2></div><a class="section-link" href="/maintenance">View all maintenance →</a></div><div class="entry-list"><?php if (!$latestMaintenance): ?><div class="empty-card">No maintenance windows have been published.</div><?php else: foreach ($latestMaintenance as $item): $slug = (string) ($item['slug'] ?? ''); ?><a class="entry-row" <?= $slug ? 'href="/maintenance/' . h($slug) . '"' : '' ?>><span class="entry-date"><?= h(format_time($item['startAt'] ?? null, 'j M Y')) ?></span><div><h3><?= h((string) ($item['title'] ?? 'Maintenance')) ?></h3><p><?= h(ucfirst((string) ($item['status'] ?? 'scheduled'))) ?> · <?= h(format_time($item['startAt'] ?? null, 'g:i A')) ?>–<?= h(format_time($item['endAt'] ?? null, 'g:i A')) ?></p></div><span class="entry-arrow">↗</span></a><?php endforeach; endif; ?></div></section>

  <section class="section-block posts-section"><div class="section-heading"><div><span class="eyebrow">From the system desk</span><h2>Latest posts</h2></div><a class="section-link" href="/posts">View all posts →</a></div><div class="post-grid"><?php if (!$latestPosts): ?><div class="empty-card span-all">No system posts have been published yet.</div><?php else: foreach ($latestPosts as $index => $post): ?><a class="post-card post-tone-<?= ($index % 3) + 1 ?>" href="/posts/<?= h((string) ($post['slug'] ?? '')) ?>"><span class="post-mark"><?= h(strtoupper(substr((string) ($post['title'] ?? 'P'), 0, 1))) ?></span><div><small><?= h(format_time($post['publishedAt'] ?? $post['createdAt'] ?? null, 'j M Y')) ?></small><h3><?= h((string) ($post['title'] ?? 'System post')) ?></h3><p><?= h((string) ($post['excerpt'] ?? 'Read the latest update from The Secretary team.')) ?></p><span>Read post →</span></div></a><?php endforeach; endif; ?></div></section>

  <section class="truth-note"><div><span class="truth-icon">✓</span><div><strong>Measured, never estimated</strong><p>Availability and response figures come only from completed five-minute checks.</p></div></div><span>Last check: <?= h(format_time($monitor['lastCheckAt'] ?? null)) ?></span></section>
</main>
