const {chromium}=require('C:/Users/diksh/.cache/codex-runtimes/codex-primary-runtime/dependencies/node/node_modules/playwright');
const fs=require('fs'),path=require('path'),http=require('http');
let baseline=false;const originals=new Map();const {execFileSync}=require('child_process');
const root=path.resolve('site');
const server=http.createServer((req,res)=>{let f=path.join(root,decodeURIComponent(req.url.split('?')[0]));if(fs.existsSync(f)&&fs.statSync(f).isDirectory())f=path.join(f,'index.html');if(!fs.existsSync(f)){res.writeHead(404);return res.end();}res.setHeader('Content-Type',({'.html':'text/html','.css':'text/css','.js':'text/javascript','.png':'image/png','.webp':'image/webp'})[path.extname(f)]||'application/octet-stream');if(baseline && /\.(html|css|js)$/.test(f)){const name=path.relative(process.cwd(),f).replaceAll('\\','/');if(!originals.has(name)){try{originals.set(name,execFileSync('git',['show','HEAD:'+name],{maxBuffer:20e6}));}catch{originals.set(name,'');}}return res.end(originals.get(name));}res.end(fs.readFileSync(f));});
(async()=>{await new Promise(r=>server.listen(8767,'127.0.0.1',r));const browser=await chromium.launch({headless:true,channel:"msedge"});const page=await browser.newPage();
await page.route('**/*',async route=>{const u=route.request().url();if(u.startsWith('http://127.0.0.1'))return route.continue();if(u.includes('supabase-js'))return route.fulfill({contentType:'text/javascript',body:`export function createClient(){
const person={id:'test',role:'admin',username:'mobiletester',display_name:'Mobile test user',avatar_path:null};
const post={id:1,slug:'test',title:'A complete mobile update with a longer headline for small screens',excerpt:'Readable content on every screen size.',content_html:'<h2>A long heading</h2><p>'+('UnbrokenContent'.repeat(30))+'</p><pre>'+('code_example_'.repeat(30))+'</pre><img src="/assets/images/post-fallback-full.webp">',full_thumb_url:'/assets/images/post-fallback-full.webp',poster_url:'/assets/images/post-fallback-poster.webp',published_at:new Date().toISOString(),status:'published',is_hero:true,is_pinned:true};
const topic={id:1,user_id:'test',slug:'test',category:'bugs',title:post.title,body:'Long content '+('LongUrlWithoutSpaces'.repeat(30)),profiles:person,status:'open',views:5,created_at:new Date().toISOString(),updated_at:new Date().toISOString()};
function from(table){let single=false;const rows=table==='profiles'?[person]:table==='posts'?[post]:table==='forum_topics'?[topic]:[];const q=new Proxy(function(){},{get:(_,k)=>k==='then'?((resolve)=>Promise.resolve(resolve({data:single?rows[0]:rows,error:null}))):()=>{if(k==='single'||k==='maybeSingle')single=true;return q;},apply:()=>q});return q;}
return {from,rpc:async()=>({data:null,error:null}),auth:{getUser:async()=>({data:{user:{id:'test'}}}),getSession:async()=>({data:{session:{access_token:'fixture'}}}),onAuthStateChange:()=>({data:{subscription:{unsubscribe(){}}}})},storage:{from:()=>({getPublicUrl:()=>({data:{publicUrl:''}})})}};
}`});if(u.includes('script.google'))return route.fulfill({contentType:'application/json',body:JSON.stringify({ok:true,monitor:{status:'operational',uptime:{30:99.8,90:99.2},history:[]},incidents:[],maintenance:[],historyEvents:[],servers:[],posts:[],items:[]})});return route.abort();});
const errors=[];page.on('pageerror',e=>errors.push(e.message));const results=[];
for(const width of [320,390,768]){await page.setViewportSize({width,height:900});for(const route of ['/admin/','/admin/posts/','/admin/incidents/','/admin/maintenance/','/admin/servers/','/admin/webhooks/','/profile/']){await page.goto('http://127.0.0.1:8767'+route);await page.waitForTimeout(100);console.log(width,route,await page.locator('h1').allTextContents());if(width===320)await page.screenshot({path:'work/admin-'+route.replaceAll('/','')+'.png',fullPage:true});const r=await page.evaluate(()=>({overflow:document.documentElement.scrollWidth>innerWidth,offenders:[...document.querySelectorAll('body *')].filter(e=>{const s=getComputedStyle(e),r=e.getBoundingClientRect();return r.width&&s.position!=='absolute'&&s.position!=='fixed'&&((r.right>innerWidth+1)||(e.scrollWidth>e.clientWidth+2&&['auto','scroll'].includes(s.overflowX)))}).map(e=>e.tagName+'.'+e.className).slice(0,8),bars:document.querySelector('.status-history')?.children.length}));if(r.overflow||r.offenders.length||r.bars)results.push({width,route,...r});if(width===390&&['/','/status/','/login/','/forums/'].includes(route))await page.screenshot({path:'work/'+(route.replaceAll('/','')||'home')+'.png',fullPage:true});}}
console.log(JSON.stringify({results,errors:[...new Set(errors)]},null,2));await browser.close();server.close();})().catch(e=>{console.error(e);server.close();process.exitCode=1});
