-- The Secretary Status 4.0 community schema for Supabase/PostgreSQL.
-- Run this entire file once in Supabase Dashboard -> SQL Editor.

create extension if not exists citext;

create table if not exists public.profiles (
  id uuid primary key references auth.users(id) on delete cascade,
  display_name varchar(80) not null,
  username citext not null unique check (username::text ~ '^[a-z0-9_]{3,32}$'),
  role text not null default 'user' check (role in ('user','moderator','admin')),
  bio varchar(600) not null default '',
  avatar_path text,
  banner_path text,
  accent_primary varchar(7) not null default '#f2eb00' check (accent_primary ~ '^#[0-9a-fA-F]{6}$'),
  accent_secondary varchar(7) not null default '#7c3aed' check (accent_secondary ~ '^#[0-9a-fA-F]{6}$'),
  profile_effect text not null default 'aurora' check (profile_effect in ('aurora','nebula','ember','ocean','none')),
  avatar_scale numeric(3,2) not null default 1 check (avatar_scale between 1 and 2),
  avatar_x smallint not null default 50 check (avatar_x between 0 and 100),
  avatar_y smallint not null default 50 check (avatar_y between 0 and 100),
  banner_y smallint not null default 50 check (banner_y between 0 and 100),
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now(),
  last_seen_at timestamptz
);

create table if not exists public.post_comments (
  id bigint generated by default as identity primary key,
  post_slug varchar(120) not null,
  user_id uuid not null references public.profiles(id) on delete cascade,
  body text not null check (char_length(body) between 1 and 5000),
  is_deleted boolean not null default false,
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now()
);

create table if not exists public.forum_topics (
  id bigint generated by default as identity primary key,
  user_id uuid not null references public.profiles(id) on delete cascade,
  category text not null check (category in ('suggestion','bugs','website-error','fatal-error','downtime')),
  title varchar(160) not null check (char_length(title) between 6 and 160),
  slug varchar(190) not null unique check (slug ~ '^[a-z0-9][a-z0-9-]{0,189}$'),
  body text not null check (char_length(body) between 10 and 20000),
  status text not null default 'open' check (status in ('open','closed','solved')),
  solution_reply_id bigint,
  views integer not null default 0 check (views >= 0),
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now()
);

create table if not exists public.forum_replies (
  id bigint generated by default as identity primary key,
  topic_id bigint not null references public.forum_topics(id) on delete cascade,
  user_id uuid not null references public.profiles(id) on delete cascade,
  parent_id bigint references public.forum_replies(id) on delete cascade,
  body text not null check (char_length(body) between 1 and 10000),
  is_deleted boolean not null default false,
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now()
);

do $$ begin
  alter table public.forum_topics add constraint forum_topics_solution_reply_fk
    foreign key (solution_reply_id) references public.forum_replies(id) on delete set null;
exception when duplicate_object then null; end $$;

create table if not exists public.forum_topic_votes (
  topic_id bigint not null references public.forum_topics(id) on delete cascade,
  user_id uuid not null references public.profiles(id) on delete cascade,
  vote smallint not null check (vote in (-1,1)),
  updated_at timestamptz not null default now(),
  primary key (topic_id,user_id)
);

create table if not exists public.forum_reply_votes (
  reply_id bigint not null references public.forum_replies(id) on delete cascade,
  user_id uuid not null references public.profiles(id) on delete cascade,
  vote smallint not null check (vote in (-1,1)),
  updated_at timestamptz not null default now(),
  primary key (reply_id,user_id)
);

create index if not exists comments_post_idx on public.post_comments(post_slug,created_at);
create index if not exists topics_activity_idx on public.forum_topics(category,updated_at desc);
create index if not exists replies_topic_idx on public.forum_replies(topic_id,created_at);

create or replace function public.touch_updated_at() returns trigger language plpgsql as $$
begin new.updated_at = now(); return new; end $$;

create or replace function public.validate_forum_reply_reference() returns trigger
language plpgsql as $$
begin
  if new.parent_id is not null and
     not exists(select 1 from public.forum_replies p where p.id=new.parent_id and p.topic_id=new.topic_id) then
    raise exception 'Parent reply must belong to the same topic.';
  end if;
  return new;
end $$;

create or replace function public.validate_forum_topic_solution() returns trigger
language plpgsql as $$
begin
  if new.solution_reply_id is not null and
     not exists(select 1 from public.forum_replies r where r.id=new.solution_reply_id and r.topic_id=new.id) then
    raise exception 'Solution reply must belong to this topic.';
  end if;
  return new;
end $$;

drop trigger if exists profiles_touch on public.profiles;
create trigger profiles_touch before update on public.profiles for each row execute function public.touch_updated_at();
drop trigger if exists comments_touch on public.post_comments;
create trigger comments_touch before update on public.post_comments for each row execute function public.touch_updated_at();
drop trigger if exists topics_touch on public.forum_topics;
create trigger topics_touch before update on public.forum_topics for each row execute function public.touch_updated_at();
drop trigger if exists replies_touch on public.forum_replies;
create trigger replies_touch before update on public.forum_replies for each row execute function public.touch_updated_at();
drop trigger if exists replies_validate_reference on public.forum_replies;
create trigger replies_validate_reference before insert or update on public.forum_replies for each row execute function public.validate_forum_reply_reference();
drop trigger if exists topics_validate_reference on public.forum_topics;
create trigger topics_validate_reference before insert or update on public.forum_topics for each row execute function public.validate_forum_topic_solution();

create or replace function public.handle_new_user() returns trigger
security definer set search_path = public language plpgsql as $$
begin
  insert into public.profiles(id,display_name,username,last_seen_at)
  values (
    new.id,
    left(coalesce(nullif(new.raw_user_meta_data->>'display_name',''),'Member'),80),
    lower(left(coalesce(nullif(new.raw_user_meta_data->>'username',''),'member_' || substr(replace(new.id::text,'-',''),1,8)),32)),
    now()
  );
  return new;
end $$;

drop trigger if exists on_auth_user_created on auth.users;
create trigger on_auth_user_created after insert on auth.users for each row execute function public.handle_new_user();

create or replace function public.is_admin() returns boolean
language sql stable security definer set search_path = public as $$
  select exists(select 1 from public.profiles where id=auth.uid() and role in ('admin','moderator'));
$$;

create or replace function public.increment_topic_views(target_id bigint) returns void
language sql security definer set search_path = public as $$
  update public.forum_topics set views=views+1 where id=target_id;
$$;

create or replace function public.resolve_login_email(login_username text) returns text
language sql security definer set search_path = public,auth as $$
  select u.email from public.profiles p join auth.users u on u.id=p.id
  where p.username=lower(trim(login_username)) limit 1;
$$;
revoke all on function public.resolve_login_email(text) from public,anon,authenticated;
grant execute on function public.resolve_login_email(text) to service_role;

alter table public.profiles enable row level security;
alter table public.post_comments enable row level security;
alter table public.forum_topics enable row level security;
alter table public.forum_replies enable row level security;
alter table public.forum_topic_votes enable row level security;
alter table public.forum_reply_votes enable row level security;

drop policy if exists profiles_public_read on public.profiles;
create policy profiles_public_read on public.profiles for select using (true);
drop policy if exists profiles_owner_update on public.profiles;
create policy profiles_owner_update on public.profiles for update using (id=auth.uid()) with check (id=auth.uid());

drop policy if exists comments_public_read on public.post_comments;
create policy comments_public_read on public.post_comments for select using (true);
drop policy if exists comments_owner_insert on public.post_comments;
create policy comments_owner_insert on public.post_comments for insert to authenticated with check (user_id=auth.uid());
drop policy if exists comments_owner_update on public.post_comments;
create policy comments_owner_update on public.post_comments for update to authenticated using (user_id=auth.uid() or public.is_admin()) with check (user_id=auth.uid() or public.is_admin());
drop policy if exists comments_owner_delete on public.post_comments;
create policy comments_owner_delete on public.post_comments for delete to authenticated using (user_id=auth.uid() or public.is_admin());

drop policy if exists topics_public_read on public.forum_topics;
create policy topics_public_read on public.forum_topics for select using (true);
drop policy if exists topics_owner_insert on public.forum_topics;
create policy topics_owner_insert on public.forum_topics for insert to authenticated with check (user_id=auth.uid());
drop policy if exists topics_owner_update on public.forum_topics;
create policy topics_owner_update on public.forum_topics for update to authenticated using (user_id=auth.uid() or public.is_admin()) with check (user_id=auth.uid() or public.is_admin());
drop policy if exists topics_admin_delete on public.forum_topics;
create policy topics_admin_delete on public.forum_topics for delete to authenticated using (public.is_admin());

drop policy if exists replies_public_read on public.forum_replies;
create policy replies_public_read on public.forum_replies for select using (true);
drop policy if exists replies_owner_insert on public.forum_replies;
create policy replies_owner_insert on public.forum_replies for insert to authenticated with check (user_id=auth.uid());
drop policy if exists replies_owner_update on public.forum_replies;
create policy replies_owner_update on public.forum_replies for update to authenticated using (user_id=auth.uid() or public.is_admin()) with check (user_id=auth.uid() or public.is_admin());

drop policy if exists topic_votes_public_read on public.forum_topic_votes;
create policy topic_votes_public_read on public.forum_topic_votes for select using (true);
drop policy if exists topic_votes_owner_write on public.forum_topic_votes;
create policy topic_votes_owner_write on public.forum_topic_votes for all to authenticated using (user_id=auth.uid()) with check (user_id=auth.uid());
drop policy if exists reply_votes_public_read on public.forum_reply_votes;
create policy reply_votes_public_read on public.forum_reply_votes for select using (true);
drop policy if exists reply_votes_owner_write on public.forum_reply_votes;
create policy reply_votes_owner_write on public.forum_reply_votes for all to authenticated using (user_id=auth.uid()) with check (user_id=auth.uid());

grant usage on schema public to anon,authenticated;
grant select on public.profiles,public.post_comments,public.forum_topics,public.forum_replies,public.forum_topic_votes,public.forum_reply_votes to anon,authenticated;
grant insert on public.post_comments,public.forum_topics,public.forum_replies,public.forum_topic_votes,public.forum_reply_votes to authenticated;
grant delete on public.post_comments,public.forum_topics,public.forum_replies,public.forum_topic_votes,public.forum_reply_votes to authenticated;
grant update(body,is_deleted,updated_at) on public.post_comments to authenticated;
grant update(status,solution_reply_id,updated_at) on public.forum_topics to authenticated;
grant update(body,is_deleted,updated_at) on public.forum_replies to authenticated;
grant update(vote,updated_at) on public.forum_topic_votes,public.forum_reply_votes to authenticated;
revoke update on public.profiles from authenticated;
grant update(display_name,bio,avatar_path,banner_path,accent_primary,accent_secondary,profile_effect,avatar_scale,avatar_x,avatar_y,banner_y,last_seen_at) on public.profiles to authenticated;
grant usage,select on all sequences in schema public to authenticated;
grant execute on function public.increment_topic_views(bigint) to anon,authenticated;

insert into storage.buckets(id,name,public,file_size_limit,allowed_mime_types)
values ('profile-media','profile-media',true,8388608,array['image/jpeg','image/png','image/webp','image/gif'])
on conflict (id) do update set public=true,file_size_limit=8388608,allowed_mime_types=excluded.allowed_mime_types;

drop policy if exists profile_media_public_read on storage.objects;
create policy profile_media_public_read on storage.objects for select using (bucket_id='profile-media');
drop policy if exists profile_media_owner_insert on storage.objects;
create policy profile_media_owner_insert on storage.objects for insert to authenticated
with check (bucket_id='profile-media' and (storage.foldername(name))[1]=auth.uid()::text);
drop policy if exists profile_media_owner_update on storage.objects;
create policy profile_media_owner_update on storage.objects for update to authenticated
using (bucket_id='profile-media' and (storage.foldername(name))[1]=auth.uid()::text)
with check (bucket_id='profile-media' and (storage.foldername(name))[1]=auth.uid()::text);
drop policy if exists profile_media_owner_delete on storage.objects;
create policy profile_media_owner_delete on storage.objects for delete to authenticated
using (bucket_id='profile-media' and (storage.foldername(name))[1]=auth.uid()::text);
