-- Queue replaced profile and post images for safe deletion after two hours.
create table if not exists public.media_cleanup_queue (
  id bigint generated by default as identity primary key,
  bucket_id text not null check (bucket_id in ('profile-media','post-media')),
  object_path text not null,
  delete_after timestamptz not null default (now() + interval '2 hours'),
  created_at timestamptz not null default now(),
  unique (bucket_id, object_path)
);

alter table public.media_cleanup_queue enable row level security;
revoke all on public.media_cleanup_queue from anon, authenticated;

create or replace function public.queue_media_cleanup(p_bucket text, p_path text)
returns void language plpgsql security definer set search_path=public as $$
begin
  if nullif(trim(p_path),'') is null then return; end if;
  insert into public.media_cleanup_queue(bucket_id,object_path,delete_after)
  values(p_bucket,trim(p_path),now()+interval '2 hours')
  on conflict(bucket_id,object_path) do update
    set delete_after=excluded.delete_after,created_at=now();
end $$;

create or replace function public.queue_replaced_profile_media()
returns trigger language plpgsql security definer set search_path=public as $$
begin
  if tg_op='DELETE' then
    perform public.queue_media_cleanup('profile-media',old.avatar_path);
    perform public.queue_media_cleanup('profile-media',old.banner_path);
    return old;
  end if;
  if old.avatar_path is distinct from new.avatar_path then perform public.queue_media_cleanup('profile-media',old.avatar_path); end if;
  if old.banner_path is distinct from new.banner_path then perform public.queue_media_cleanup('profile-media',old.banner_path); end if;
  return new;
end $$;

drop trigger if exists profiles_queue_replaced_media on public.profiles;
create trigger profiles_queue_replaced_media after update of avatar_path,banner_path or delete on public.profiles
for each row execute function public.queue_replaced_profile_media();

create or replace function public.queue_replaced_post_media()
returns trigger language plpgsql security definer set search_path=public as $$
declare item jsonb; item_path text;
begin
  if tg_op='DELETE' then
    perform public.queue_media_cleanup('post-media',old.full_thumb_path);
    perform public.queue_media_cleanup('post-media',old.poster_path);
    for item in select value from jsonb_array_elements(coalesce(old.gallery,'[]'::jsonb)) loop
      perform public.queue_media_cleanup('post-media',item->>'path');
    end loop;
    return old;
  end if;
  if old.full_thumb_path is distinct from new.full_thumb_path then perform public.queue_media_cleanup('post-media',old.full_thumb_path); end if;
  if old.poster_path is distinct from new.poster_path then perform public.queue_media_cleanup('post-media',old.poster_path); end if;
  for item in select value from jsonb_array_elements(coalesce(old.gallery,'[]'::jsonb)) loop
    item_path:=item->>'path';
    if item_path is not null and not exists(select 1 from jsonb_array_elements(coalesce(new.gallery,'[]'::jsonb)) n where n->>'path'=item_path) then
      perform public.queue_media_cleanup('post-media',item_path);
    end if;
  end loop;
  return new;
end $$;

drop trigger if exists posts_queue_replaced_media on public.posts;
create trigger posts_queue_replaced_media after update of full_thumb_path,poster_path,gallery or delete on public.posts
for each row execute function public.queue_replaced_post_media();

create or replace function public.discover_orphan_media_cleanup()
returns integer language plpgsql security definer set search_path=public as $$
declare queued integer;
begin
  insert into public.media_cleanup_queue(bucket_id,object_path,delete_after)
  select o.bucket_id,o.name,now()
  from storage.objects o
  where o.bucket_id in ('profile-media','post-media')
    and o.created_at<=now()-interval '2 hours'
    and not exists(select 1 from public.profiles p where o.bucket_id='profile-media' and o.name in (p.avatar_path,p.banner_path))
    and not exists(select 1 from public.posts p where o.bucket_id='post-media' and (
      o.name in (p.full_thumb_path,p.poster_path)
      or coalesce(p.gallery,'[]'::jsonb) @> jsonb_build_array(jsonb_build_object('path',o.name))
      or position(o.name in coalesce(p.content_html,''))>0
    ))
  on conflict(bucket_id,object_path) do nothing;
  get diagnostics queued=row_count;
  return queued;
end $$;
create or replace function public.due_unused_media_cleanup(batch_size integer default 100)
returns table(id bigint,bucket_id text,object_path text)
language sql security definer set search_path=public stable as $$
  select q.id,q.bucket_id,q.object_path
  from public.media_cleanup_queue q
  where q.delete_after<=now()
    and not exists(select 1 from public.profiles p where q.bucket_id='profile-media' and q.object_path in (p.avatar_path,p.banner_path))
    and not exists(select 1 from public.posts p where q.bucket_id='post-media' and (
      q.object_path in (p.full_thumb_path,p.poster_path)
      or coalesce(p.gallery,'[]'::jsonb) @> jsonb_build_array(jsonb_build_object('path',q.object_path))
      or position(q.object_path in coalesce(p.content_html,''))>0
    ))
  order by q.delete_after
  limit greatest(1,least(coalesce(batch_size,100),500));
$$;

create or replace function public.complete_media_cleanup(cleanup_id bigint)
returns void language sql security definer set search_path=public as $$
  delete from public.media_cleanup_queue where id=cleanup_id;
$$;
revoke all on function public.queue_media_cleanup(text,text),public.discover_orphan_media_cleanup(),public.due_unused_media_cleanup(integer),public.complete_media_cleanup(bigint) from public,anon,authenticated;
grant execute on function public.discover_orphan_media_cleanup(),public.due_unused_media_cleanup(integer),public.complete_media_cleanup(bigint) to service_role;
